version: "3.9"
services:
  api:
    build: .
    ports: ["8000:8000"]
    env_file: [.env]
    depends_on: [db]
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: danguy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports: ["5432:5432"]
